global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # Метрики самого Prometheus.
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  # Системные метрики Linux, которые отдаёт Node Exporter.
  - job_name: node
    static_configs:
      - targets: ["localhost:9100"]
